### ISSUE TITLE
One help

### ISSUE THREAD

**Issue by BX-xb** [Yacnnn/MVGCCA#1]
Thanks for the author's excellent work, could you please provide the code of the comparison experiment GMCCA (Graph-Aware Multiview CCA method) ?
Much appreciate!

**Comment by Yacnnn** [comment]
Hello,

	I published my code yesterday here : https://github.com/Yacnnn/MVGCCA <https://github.com/Yacnnn/MVGCCA>

You can reproduce experiments with this. However I will make updates and add all experiments.

Best regards,
